# -*- coding: utf-8 -*-
"""
Created on Wed Oct 31 13:50:31 2018

@author: aelshaha
"""


class EVENTS():

    YEAR_ADDING = "YEAR_ADDING_"
    YEAR_ADDED = "YEAR_ADDED_"
    YEAR_REMOVING = "YEAR_REMOVING_"
    YEAR_REMOVED = "YEAR_REMOVED_"

    SITE_ADDING = "SITE_ADDING_"
    SITE_ADDED = "SITE_ADDED_"
    SITE_REMOVING = "SITE_REMOVING_"
    SITE_REMOVED = "SITE_REMOVED_"

    PERIOD_ADDING = "PERIOD_ADDING_"
    PERIOD_ADDED = "PERIOD_ADDED_"
    PERIOD_REMOVING = "PERIOD_REMOVING_"
    PERIOD_REMOVED = "PERIOD_REMOVED_"

    RES_SELECTED = "RES_SELECTED_"

    COMMODITY_ADDING = "COMMODITY_ADDING_"
    COMMODITY_ADDED = "COMMODITY_ADDED_"
    COMMODITY_EDITING = "COMMODITY_EDITING_"
    COMMODITY_EDITED = "COMMODITY_EDITED_"
    COMMODITY_SAVE = "COMMODITY_SAVE_"
    COMMODITY_REMOVING = "COMMODITY_REMOVING_"
    COMMODITY_REMOVED = "COMMODITY_REMOVED_"
    COMMODITY_SELECTED = "COMMODITY_SELECTED_"
    COMMODITY_DESELECTED = "COMMODITY_DESELECTED_"

    PROCESS_ADDING = "PROCESS_ADDING_"
    PROCESS_ADDED = "PROCESS_ADDED_"
    PROCESS_EDITING = "PROCESS_EDITING_"
    PROCESS_EDITED = "PROCESS_EDITED_"
    PROCESS_SAVE = "PROCESS_SAVE_"
    PROCESS_REMOVING = "PROCESS_REMOVING_"
    PROCESS_REMOVED = "PROCESS_REMOVED_"
    PROCESS_SELECTED = "PROCESS_SELECTED_"
    PROCESS_DESELECTED = "PROCESS_DESELECTED_"

    CONNECTION_EDITING = "CONNECTION_EDITING_"

    STORAGE_ADDING = "STORAGE_ADDING_"
    STORAGE_ADDED = "STORAGE_ADDED_"
    STORAGE_EDITING = "STORAGE_EDITING_"
    STORAGE_EDITED = "STORAGE_EDITED_"
    STORAGE_SAVE = "STORAGE_SAVE_"

    TRNSM_ADDING = "TRNSM_ADDING_"
    TRNSM_ADDED = "TRNSM_ADDED_"
    TRNSM_EDITING = "TRNSM_EDITING_"
    TRNSM_EDITED = "TRNSM_EDITED_"
    TRNSM_SAVE = "TRNSM_SAVE_"

    ITEM_DOUBLE_CLICK = "ITEM_DOUBLE_CLICK_"
    ITEM_MOVED = "ITEM_MOVED_"
    ITEM_COPY = "ITEM_COPY_"
    ITEM_COPIED = "ITEM_COPIED_"
    ITEM_DELETE = "ITEM_DELETE_"
    ITEM_DELETED = "ITEM_DELETED_"
    ITEM_CLONE = "ITEM_CLONE_"
    TRNSM_ITEM_MOVED = "TRNSM_ITEM_MOVED_"
    SAVE_CONFIG = "SAVE_CONFIG_"
    LOAD_CONFIG = "LOAD_CONFIG_"

    GL_PARAMS_LOADED = "GL_PARAMS_LOADED_"

    SCENARIOS_LOADED = "SCENARIOS_LOADED_"
    SCENARIO_ADDED = "SCENARIO_ADDED_"
    SCENARIO_REMOVED = "SCENARIO_REMOVED_"
